### ISSUE TITLE
return values of coordinate_x functions in blackbox l2 attacks

### ISSUE THREAD

**Issue by dionman** [IBM/ZOO-Attack#1]
It seems to me that the coordinate_adam,.. functions in the l2-based blackbox attack script as currently written do not return any values or affect any of the class attributes. Is this correct? How is coordinate_adam(args) affecting args or the remainder of the computation?

**Comment by huanzhang12** [comment]
The function updates variables (numpy arrays) in place. The args are passed by reference.
